#! /bin/sh
set -e
 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="php-fpm daemon"
NAME=php-fpm
DAEMON=/usr/local/php5/sbin/$NAME
PIDFILE=/usr/local/php5/var/log/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
 
# Gracefully exit if the package has been removed.


d_start() {
  /usr/local/php5/sbin/php-fpm > /dev/null 2>&1 
}
 
d_stop() {
  /bin/kill -SIGINT `cat /usr/local/php5/var/run/php-fpm.pid` > /dev/null 2>&1 
}

d_restart() {
  /bin/kill -SIGUSE2 `cat /usr/local/php5/var/run/php-fpm.pid`  > /dev/null 2>&1
}
 
case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        d_start
        echo "."
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        d_stop
        echo "."
        ;;
  restart)
        echo -n "Restarting $DESC: $NAME"
        d_stop
        sleep 1
        d_start
        echo "."
        ;;
  *)
          echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
          exit 3
        ;;
esac
 
exit 0
